import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const clashDisplay = localFont({
  src: [
    {
      path: "./fonts/ClashDisplay-Extralight.otf",
      weight: "200",
    },
    {
      path: "./fonts/ClashDisplay-Light.otf",
      weight: "300",
    },
    {
      path: "./fonts/ClashDisplay-Regular.otf",
      weight: "400",
    },
    {
      path: "./fonts/ClashDisplay-Medium.otf",
      weight: "500",
    },
    {
      path: "./fonts/ClashDisplay-Semibold.otf",
      weight: "600",
    },
    {
      path: "./fonts/ClashDisplay-Bold.otf",
      weight: "700",
    },
  ],
  variable: "--font-clash-display",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${clashDisplay.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
